name: Sung-Jun Portfolio

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout code
      #  uses: actions/checkout@v2
      - name: Run pwd
        run: pwd
      - name: Run ls -al
        run: ls -al
      #- name: Build code
      #  run: npm run build
      #- name: Test code
      #  run: npm test
